{"name": "Проверка ошибки при попытке удаления курьера без указания id", "status": "passed", "steps": [{"name": "Удаление курьера", "status": "passed", "parameters": [{"name": "courier_id", "value": "''"}], "start": 1747299820065, "stop": 1747299820153}], "start": 1747299820065, "stop": 1747299820154, "uuid": "a1436aeb-d089-44ee-a054-2d59a60b4d63", "historyId": "0b46b44121eabc736bf51ec5ad9d7f19", "testCaseId": "0b46b44121eabc736bf51ec5ad9d7f19", "fullName": "tests.test_couriers.test_courier_delete.TestCourierDelete#test_courier_delete_error_with_empty_id", "labels": [{"name": "parentSuite", "value": "tests.test_couriers"}, {"name": "suite", "value": "test_courier_delete"}, {"name": "subSuite", "value": "TestCourierDelete"}, {"name": "host", "value": "DESKTOP-VE6DRBG"}, {"name": "thread", "value": "8232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_couriers.test_courier_delete"}]}